services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo:/data/db
    expose:
      - 27017
    ports:
      - '27017:27017'    restart: on-failure
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/admin",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  api-monsters:
    build: ../api-monsters/demo
    container_name:  api-monster
    ports:
      - "8080:8080"    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy


  api-authenticator:
    build: ../api-authenticator/demo
    container_name:  api-authenticator
    ports:
      - "8081:8080"    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy

  api-player:
    build: ../api-player/demo
    container_name: api-player
    ports:
      - "8082:8080"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy

  api-invocation:
    build: ../api-invocation/demo
    container_name: api-invocation
    ports:
      - "8083:8080"
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy


  # frontend:
    # build: ../app
    # ports:
      # - "3000:3000"
    # volumes:
      # - ../app:/app
      # - /app/node_modules
    # stdin_open: true
    # tty: true
    # depends_on:
      # - api-invocation
      # - api-player
      # - api-monsters
      # - api-authenticator

volumes:
  mongo:
